### ISSUE TITLE
Polymorphing Immunity perk mod not detected (Noita v23.04 GOG)

### ISSUE THREAD

**Issue by OutbackCatgirl** [Purpzie/start_perks#2]
The Polymorphing Immunity mod (https://modworkshop.net/mod/27206) is over a year old but still works just fine. 

It adds the new perk to the existing perk list, but it seems that regardless of mod order and whether or not i'm ingame, this one doesn't seem to show up. No idea why, and I will not be surprised if it does turn out i'm doing something wrong to cause this to occur.

Just for your reference, this is how that mod handles adding said perk, in case anything jumps out at you as off. 

init:

```dofile("data/scripts/perks/perk_list.lua")
ModLuaFileAppend("data/scripts/perks/perk_list.lua", "mods/polymorphing_immunity/files/script.lua")
```

script:

```dofile("data/scripts/lib/utilities.lua")

table.insert(
	perk_list,
	{
		id = "PROTECTION_POLYMORPHING",
		ui_name = "Polymorphing Immunity",
		ui_description = "Polymorphing has no effect on you.",
		ui_icon = "mods/polymorphing_immunity/files/ui_gfx.png",
		perk_icon = "mods/polymorphing_immunity/files/item_gfx.png",

		func = function(entity_perk_item, entity_who_picked, item_name)
			EntityAddTag(entity_who_picked, "polymorphable_NOT")
		end,
	}
)
```

Since i'm using the GOG version, i usually archive copies of each version of Noita. If you think it would be safe for me to manually edit the vanilla script file to add this perk and if you think that would work it is an option i'm tempted to try just to get it playing nicely. Or if you have another solution or insight let me know <3

**Comment by Purpzie** [comment]
Apologies for the long wait, I haven't played Noita for a long time but recently got back into it.

Strangely it's showing up when using `noita_dev.exe` but not using the regular `noita.exe`. Currently trying to figure out what's going on.

**Comment by OutbackCatgirl** [comment]
> Apologies for the long wait, I haven't played Noita for a long time but recently got back into it.
> 
> Strangely it's showing up when using `noita_dev.exe` but not using the regular `noita.exe`. Currently trying to figure out what's going on.

Same! Interesting that it detects properly in devmode, I never thought of even trying that. Best of luck finding out the cause :D

Edit:
Hmmm, doesn't show up in dev mode for me. I did notice a bunch of "failed to load xml file..." errors in the log but idk if that's just normal.
